const admin = require("firebase-admin");

console.log("🔐 Lecture de la clé FIREBASE_KEY...");
if (!process.env.FIREBASE_KEY) {
  throw new Error("❌ Erreur : FIREBASE_KEY introuvable.");
}

let parsedKey;
try {
  parsedKey = JSON.parse(process.env.FIREBASE_KEY);
} catch (err) {
  throw new Error("❌ Erreur : la clé FIREBASE_KEY n'est pas un JSON valide.");
}

admin.initializeApp({
  credential: admin.credential.cert(parsedKey),
  databaseURL: "https://projecttogether-26e40-default-rtdb.europe-west1.firebasedatabase.app",
});

const db = admin.database();

const mois = "2025-07";

// 🗳️ Les données à restaurer
const votes = {
  "Poissegrolle": 145,
  "Tris": 119,
  "Jean_ro": 97,
  "Poissongrolle": 78,
  "Nova": 77,
  "Vyktor": 65,
  "ToonsFlib": 56,
  "Traffy": 48,
  "Maverick": 45,
  "Noteca": 44,
  "Apo": 43,
  "AzogMikou": 43,
  "Aethernal": 39,
  "Ajiwah": 32,
  "Michonne": 29,
  "Ouroboros": 26,
  "Rist": 26,
  "Patrick_Bruel": 25,
  "sirt": 24,
  "Parrish_FR": 23,
  "Koni": 22,
  "Sidrus": 21,
  "LeClodo": 20,
  "TRX": 20,
  "Loiseaugrolle": 17,
  "Zormi": 17,
  "Poissongrolle2": 16,
  "Valéria": 16,
  "Dr_Mayonnnaise": 14,
  "4L3X1S": 13,
  "Marion": 13,
  "MOUFLON69": 11,
  "Calimeros": 10,
  "Tavoc": 10,
  "Laurie": 9,
  "Rosaria": 9,
  "Tobby": 9,
  "GilouBrown": 8,
  "PoissonChaussure": 8,
  "darkgreenazd": 8,
  "4L3X1S2": 7,
  "AzogMikou2": 7,
  "JohnnyGuitar": 7,
  "2grolles": 6,
  "Halvard": 6,
  "Hero___Gorge": 6,
  "ToonsFliblecultiste": 6,
  "Emma_Cookz": 5,
  "Poissegrolle2": 5,
  "SoulsHunter": 5,
  "4lch3mist": 4,
  "Braskho": 4,
  "gentil_jaune": 4,
  "Anthelme": 3,
  "Auclairdelagrolle": 3,
  "Jonathan_Lévêque": 3,
  "Kosmi": 3,
  "LeFran": 3,
  "Shaka": 3,
  "Taxone": 3,
  "cana": 3,
  "drk": 3,
  "jjiro": 3,
  "Ajawah": 2,
  "AlexLeNoob": 2,
  "AlexLeZgeg": 2,
  "AnthelmeLeSodomisateurDeTris": 2,
  "Aowk": 2,
  "Arioxep": 2,
  "Ckila": 2,
  "GloireAuCulte": 2,
  "Lapoisse": 2,
  "Magrollemabataille": 2,
  "Meji": 2,
  "Rhisnes_t_une_merde": 2,
  "TrisLaCatin": 2,
  "Zooave": 2,
  "ravelski": 2,
  "_4": 1,
  "_2pac": 1,
  "Aetherna": 1,
  "Ajuwah": 1,
  "AlexEtsonKist": 1,
  "AnthelmeLeSodomisateurCosmique": 1,
  "Anti_tris": 1,
  "AzogMikou_Cultiste": 1,
  "Azztek": 1,
  "Baka_exe": 1,
  "Chacunsagrolle": 1,
  "Chippeurarrêtedechipper": 1,
  "CmoiValou": 1,
  "Coco": 1,
  "Danstesgrolle": 1,
  "Darkgrennazd": 1,
  "DeuxGrolles": 1,
  "Dr_Mayonnaise": 1,
  "Drama_gang": 1,
  "Ez": 1,
  "Ezz_vote": 1,
  "Fryboy": 1,
  "Gloire_au_culte": 1,
  "Grolle2": 1,
  "GrolleNocturne": 1,
  "HeavyZ": 1,
  "Infection_Scanner": 1,
  "Infection_scanner_V2": 1,
  "JeanRo": 1,
  "John_Racine": 1,
  "Karnimata": 1,
  "Katatraf": 1,
  "Koro": 1,
  "Kwoa": 1,
  "La_taupe": 1,
  "Liberer_PArrish": 1,
  "Lucy": 1,
  "LunaLatk": 1,
  "Maman_de_poisse": 1,
  "Mayonnaise": 1,
  "Michel": 1,
  "Midnight": 1,
  "MonPafSurTonNez": 1,
  "Monamislagrolle": 1,
  "Mr_pickles": 1,
  "OUBLIEZPASDEVOTER": 1,
  "Oh_mince": 1,
  "Papy_le_beau_goss": 1,
  "PoisseChaussure": 1,
  "PoisseLepoissonPourri": 1,
  "Poissedodo": 1,
  "PoissegrolleLeFaux": 1,
  "PoissegrolleLevrai": 1,
  "PoissonBienRemplis": 1,
  "Pourquoi_tes_de_la_police": 1,
  "Ravelski_Bondebarabe": 1,
  "Ravelski_Palkov": 1,
  "Rhines_tes_nul": 1,
  "Rhisnes_t_guez": 1,
  "Rhisnes_t_guez_de_ouf": 1,
  "SHOPOPERATIONNEL": 1,
  "SanGoyim": 1,
  "Sanrys": 1,
  "Sieur_de_la_Grolle": 1,
  "Simone": 1,
  "Sinnay": 1,
  "Sounsoun": 1,
  "TRX2": 1,
  "TRX3": 1,
  "Ta_Soeur": 1,
  "Taxone_cest_abusé": 1,
  "Traffy4G": 1,
  "Traffy_": 1,
  "Tris_heureux": 1,
  "Tris_tu_sais_pas_traduire": 1,
  "TrisLaGrosseCatin": 1,
  "Trispetitkiki": 1,
  "Tête_de_mule": 1,
  "Une_revenante": 1,
  "Van_Helsing": 1,
  "Vilainpetitplagieur": 1,
  "Zelyy": 1,
  "aowK_a_ban_Parrish": 1,
  "aowK_m_a_DDOS": 1,
  "poisssegrolle": 1,
  "rend_mon_masque_de_soudure": 1,
  "steamdown": 1
};

(async () => {
  try {
    await db.ref(`votes/${mois}`).set(votes);
    console.log(`✅ ${Object.keys(votes).length} pseudos restaurés pour le mois ${mois}.`);
  } catch (err) {
    console.error("❌ Erreur pendant la restauration :", err);
  }
})();
console.log("🔄 Restauration terminée.") ;